# 查看输出hdf5数据结构

In [3]:
# Y00855ND: 10m 6.5s
!cargo run -- -i Y00855ND.tissue.gem.gz

   Compiling gem2gef v0.1.0 (/Volumes/MacPassport/rust/geftools_rs)

 --> src/bgef_writer.rs:3:12
  |
3 | use hdf5::{types::VarLenUnicode, File as H5File, H5Type};
  |            ^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

  --> src/bgef_writer.rs:34:13
   |
34 |         let f = H5File::create(&self.output)?;
   |             ^ help: if this is intentional, prefix it with an underscore: `_f`
   |
   = note: `#[warn(unused_variables)]` on by default

  --> src/bgef_writer.rs:30:9
   |
30 |         bin: Vec<u16>,
   |         ^^^ help: if this is intentional, prefix it with an underscore: `_bin`

  --> src/bgef_writer.rs:31:9
   |
31 |         resolution: u16,
   |         ^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_resolution`

  --> src/bgef_writer.rs:14:8
   |
14 | struct BgefWriter {
   |        ^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

  --> src/bgef_writer.rs:27:8
   |
26 | impl BgefWriter {
   | ----

In [5]:
import os
import h5py
display(os.getcwd())

def print_structure(name, obj):
    if isinstance(obj, h5py.Group):
        print(f"[Group] {name}")
    elif isinstance(obj, h5py.Dataset):
        print(f"[Dataset] {name}  shape={obj.shape}  dtype={obj.dtype}")

path = "/Volumes/MacPassport/project/bioinformatics_project/MCAO20250929/data/test.bgef"
path = "dummy.bgef"
with h5py.File(path, "r") as f:
    f.visititems(print_structure)

'/Volumes/MacPassport/rust/geftools_rs'

[Group] geneExp
[Group] geneExp/bin1
[Dataset] geneExp/bin1/exon  shape=(123192319,)  dtype=uint32
[Dataset] geneExp/bin1/expression  shape=(123192319,)  dtype=[('x', '<i4'), ('y', '<i4'), ('count', '<u4')]
[Dataset] geneExp/bin1/gene  shape=(43520,)  dtype=[('gene_id', 'O'), ('gene_name', 'O'), ('offset', '<u4'), ('count', '<u4')]
[Group] stat
[Dataset] stat/gene  shape=(3,)  dtype=[('gene_id', '<u4'), ('gene_name', '<u4'), ('mid_count', '<u4'), ('log10_mid', '<f4')]
[Group] wholeExp
[Dataset] wholeExp/bin1  shape=(17502, 17043)  dtype={'names': ['mid_count', 'gene_count'], 'formats': ['<u4', '<u2'], 'offsets': [0, 4], 'itemsize': 8}
[Group] wholeExpExon
[Dataset] wholeExpExon/bin1  shape=(17502, 17043)  dtype=uint32


In [6]:
path = "/Volumes/MacPassport/project/bioinformatics_project/MCAO20250929/data/test.bgef"
path = "dummy.bgef"
with h5py.File(path, "r") as f:
    # 打印所有根级属性的名称
    print("Root attributes:", list(f["/wholeExp/bin1"].attrs.keys()))

    # # 读取单个属性
    # if "Omics" in f.attrs:
    #     print("Omics =", f.attrs["Omics"].decode() if isinstance(f.attrs["Omics"], bytes) else f.attrs["Omics"])

    # 或者一次性读取所有键值对
    for k, v in f["/wholeExp/bin1"].attrs.items():
        # 一些属性是 bytes，需要手动 decode
        if isinstance(v, bytes):
            v = v.decode()
        print(f"{k}: {v}")

Root attributes: ['lenX', 'lenY', 'maxGene', 'maxMID', 'minX', 'minY', 'number', 'resolution']
lenX: 17502
lenY: 17043
maxGene: 48
maxMID: 19
minX: 2573
minY: 4823
number: 69099850
resolution: 500


Y00855ND.tissue.gem.gz文件总行数是123196419

In [9]:
!gzcat Y00855ND.tissue.gem.gz | wc -l 

 123196419


In [9]:
# 代码示例
import h5py
import numpy as np
path = "/Volumes/MacPassport/project/bioinformatics_project/MCAO20250929/data/test.bgef"
path = "dummy.bgef"
with h5py.File(path, "r") as f:
    # h5path = "/geneExp/bin1/expression"
    h5path = "/wholeExpExon/bin1"

    # 输出属性
    print(">>>Attribute:")
    for k, v in f[h5path].attrs.items():
        # 一些属性是 bytes，需要手动 decode
        if isinstance(v, bytes):
            v = v.decode()
        print(f"{k}: {v}, {v.dtype}")
    
    # 数据矩阵
    print(">>>Dataset:")
    expr = np.array(f[h5path]) # 替换这里f的键值即可
    print(expr.shape, expr)

>>>Attribute:
maxExon: 28, uint32
>>>Dataset:
(17502, 17043) [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
